#!/bin/bash
#SBATCH -N 1
#SBATCH -C cpu
#SBATCH --qos=debug
#SBATCH -J upctest 
#SBATCH --ntasks-per-node=64
#SBATCH -t 00:10:00


#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application:
srun ./kmer_hash_19 /global/cfs/cdirs/m4341/cs5220/hw5-dataset/smaller/small.txt 
